name: .NET CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore TestRailway.sln

      - name: Build
        run: dotnet build TestRailway.sln

      - name: Test
        run: dotnet test TestRailway.sln --no-build --verbosity normal
  
  deploy: 

    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          ConnectionStrings.Default: ${{ secrets.DB_CONNECTION_STRING }}
      
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true